services:
  postgres:
    image: postgres:18
    container_name: pg_snapshot_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: snapshot_demo
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_replication_slots=10"
      - "-c"
      - "max_wal_senders=10"
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql

  clickhouse:
    image: clickhouse/clickhouse-server:26.3
    container_name: pg_snapshot_clickhouse
    environment:
      CLICKHOUSE_DB: snapshot_demo
      CLICKHOUSE_USER: snapshot_user
      CLICKHOUSE_PASSWORD: snapshot_password
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  postgres_data:
  clickhouse_data:
